Repository fpv-wtf/wtfos-configurator, pull requests merged in 2023-05, with the labels that each got.

#342 Add package config support for ui-schema
  package.json
  src/features/package/FieldHelpTemplate.jsx
  src/features/package/Package.jsx
  src/features/package/packageSlice.js
  src/utils/AdbWrapper.js
  yarn.lock
Labels: enhancement

#360 Feature/358 show warning no firmware file
  src/features/root/Root.jsx
  src/translations/de/root.json
  src/translations/el/root.json
  src/translations/en/root.json
  src/translations/es/root.json
  src/translations/fr/root.json
  src/translations/it/root.json
  src/translations/nl/root.json
  src/translations/pl/root.json
  src/translations/pt-BR/root.json
  src/translations/pt-PT/root.json
  src/translations/ru/root.json
  src/translations/sk/root.json
  src/translations/sv/root.json
  src/translations/tr/root.json
  src/translations/uk/root.json
  src/translations/vi/root.json
  src/translations/zh-CN/root.json
  src/translations/zh-TW/root.json
  src/utils/exploit/Exploit.js
  src/utils/exploit/devices.js
Labels: bugfix

#361 Soft link to wtfOS installtion #346
  src/features/setup/SetupHint.jsx
Labels: chore

#362 Show disclaimer about known application interfering with root process…
  src/features/root/Root.jsx
  src/translations/en/root.json
Labels: chore

#371 Remove CORS proxy for the rooting process.
  src/features/root/Root.jsx
  src/utils/exploit/Exploit.js
Labels: chore
